version: 2.1

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build Source 
          command: mvn -f reactive-websockets/pom.xml clean install
      - run:
          name: Build Test 
          command: mvn -f reactive-websockets-test/pom.xml clean install -DskipTests=false
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit 

workflows:
  sample: 
    jobs:
      - build-and-test
