server:
  port: 8085
spring:
  logging:
    level:
      org.springframework.web: DEBUG
      org.elpis: DEBUG
  application:
    name: websockets-test

management:
  endpoints:
    web:
      exposure:
        include: prometheus
