server:
  port: 8443
  ssl:
    key-store: classpath:ssl.p12
    key-store-password: changeit
    key-password: changeit

spring:
  logging:
    level:
      org.springframework.web: DEBUG
      org.elpis: DEBUG
  application:
    name: websockets-test

management:
  endpoints:
    web:
      exposure:
        include: prometheus
